# Define base paths first with anchor
output_root: &output_root /Users/tod/BERT_TRAINING

# Define directory paths
dirs: &dirs
  best_trials: best_trials
  evaluation: evaluation_results
  logs: logs
  data: &data_dir data
  bert_encoder: bert_encoder

# Define absolute paths using anchors
paths:
  # Fix: use proper path construction for data_root
  data_root: !join [*output_root, /, *data_dir]  # This will correctly join the paths

# Data files with absolute paths
data:
  files:
    # Use the correct data_root anchor for all files
    default: !join [*output_root, /, *data_dir, /, bbc-text.csv]
    train: !join [*output_root, /, *data_dir, /, train.csv]
    val: !join [*output_root, /, *data_dir, /, val.csv]
    test: !join [*output_root, /, *data_dir, /, test.csv]

# Model defaults
model:
  max_seq_len: 64
  batch_size: 32
  num_epochs: 10
  device: cpu
  metric: f1
  metrics: ["accuracy", "f1", "precision", "recall"]

# Classifier architecture defaults
classifier:
  bert_hidden_size: 384
  hidden_dims: [412, 220, 118]  # These will be the hidden layer sizes
  dropout_rate: 0.3499496966142211
  activation: gelu
  num_classes: 5

# Optimizer configuration
optimizer: 
  optimizer_choice: adamw  # One of: rmsprop, sgd, adamw
  lr: 0.0030733180101378092
  weight_decay: 0.005849785104191507
  warmup_ratio: 0.16512063874129088
  # RMSprop specific
  momentum: 0.367  # Used by both RMSprop and SGD
  alpha: 0.864    # RMSprop only
  # SGD specific
  nesterov: true  # SGD only
  # AdamW specific
  betas: (0.6556849067584876, 0.9989954180359887)      # AdamW only
  eps: 2.9849547332547365e-07       # AdamW only