# Define base paths first with anchor
output_root: &output_root /Users/tod/BERT_TRAINING

# Model paths (updated to use absolute paths)
model_paths:
  bert_encoder: !join [*output_root, bert_encoder]  # This creates /Users/tod/BERT_TRAINING/bert_encoder

# Define directory paths
dirs: &dirs
  best_trials: best_trials
  evaluation: evaluation_results
  logs: logs
  data: &data_dir data

# Define absolute paths using anchors
paths:
  # Fix: use proper path construction for data_root
  data_root: !join [*output_root, /, *data_dir]  # This will correctly join the paths

# Data files with absolute paths
data:
  files:
    # Use the correct data_root anchor for all files
    default: !join [*output_root, /, *data_dir, /, bbc-text-with-ids.csv]
    train: !join [*output_root, /, *data_dir, /, train.csv]
    val: !join [*output_root, /, *data_dir, /, val.csv]
    test: !join [*output_root, /, *data_dir, /, test.csv]
    predict: !join [*output_root, /, *data_dir, /, test.csv]  # Default prediction file

# Model defaults
model:
  max_seq_len: 64
  batch_size: 32
  num_epochs: 10
  device: mps
  metric: f1
  metrics: ["accuracy", "f1", "precision", "recall"]

# Classifier architecture defaults
classifier:
  # bert_hidden_size: 768
  bert_hidden_size: 384
  hidden_dims: [220]  # These will be the hidden layer sizes
  dropout_rate: 0.4396
  activation: prelu
  num_classes: 5

# Optimizer configuration
optimizer: 
  optimizer_choice: rmsprop                       # One of: rmsprop, sgd, adamw
  lr: 0.000004
  weight_decay: 0.000013
  warmup_ratio: 0.1385                            # Add warmup_ratio with default value
  momentum: 0.0000                                # RMSprop and SGD only
  alpha: 0.9900                                   # RMSprop only
  nesterov: true                                  # SGD only
  betas: (0.6556849067584876, 0.9989954180359887) # AdamW only
  eps: 2.9849547332547365e-07                     # AdamW only

# Sampler configuration
sampler:
  name: tpe
  kwargs:
    n_startup_trials: 15
    n_ei_candidates: 30

# Pruner configuration
pruner:
  name: median
