# Directory structure
output_root: /Users/tod/BERT_TRAINING
dirs:
  best_trials: best_trials
  evaluation: evaluation_results
  logs: logs
  data: data

# Model paths
model_paths:
  bert_encoder: bert_encoder  # Path relative to output_root

# Data paths
data:
  default_file: bbc-text-10.csv  # Just the filename, will be relative to data_dir

# Model defaults
model:
  max_seq_len: 64
  batch_size: 32
  num_epochs: 10
  device: cpu
  metric: f1
  metrics: ["accuracy", "f1", "precision", "recall"]

# Classifier architecture defaults
classifier:
  bert_hidden_size: 384
  hidden_dims: [412, 220, 118]  # These will be the hidden layer sizes
  dropout_rate: 0.3499496966142211
  activation: gelu
  num_classes: 5

# Optimizer configuration
optimizer: 
  optimizer_choice: adamw  # One of: rmsprop, sgd, adamw
  lr: 0.0030733180101378092
  weight_decay: 0.005849785104191507
  warmup_ratio: 0.16512063874129088
  # RMSprop specific
  momentum: 0.367  # Used by both RMSprop and SGD
  alpha: 0.864    # RMSprop only
  # SGD specific
  nesterov: true  # SGD only
  # AdamW specific
  betas: (0.6556849067584876, 0.9989954180359887)      # AdamW only
  eps: 2.9849547332547365e-07       # AdamW only